COMMENT ON COLUMN t_usrdbsvraut_i.script_cng_aut_yn IS '배치_설정_권한_여부';
COMMENT ON COLUMN t_usrdbsvraut_i.script_his_aut_yn IS '배치_이력_권한_여부';

UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 화면' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0125';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 조회' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0125_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 삭제' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0125_02';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 등록 팝업' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0126';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 등록' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0126_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 수정 팝업' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0127';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 수정' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0127_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치이력 화면' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0128';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치이력 조회' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0128_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치' WHERE GRP_CD = 'TC0019' AND SYS_CD = 'TC001902';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '배치설정 스케줄조회' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0125_03';


