INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0125_03', '스크립트설정 스케줄조회', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0026_03', 'Online 백업 상세조회 팝업', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0026_04', 'Dump 백업 상세조회 팝업', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());

INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0133_02', '복원이력 긴급/시점 복원이력 조회', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0133_03', '복원이력 Dump 복원이력 조회', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0001', 'DX-T0133_04', '복원이력 로그 조회', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());

ALTER TABLE T_DUMP_RESTORE ADD COLUMN blobs_only_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE T_DUMP_RESTORE ADD COLUMN no_unlogged_table_data_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE T_DUMP_RESTORE ADD COLUMN use_column_inserts_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE T_DUMP_RESTORE ADD COLUMN use_column_commands_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE T_DUMP_RESTORE ADD COLUMN oids_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE T_DUMP_RESTORE ADD COLUMN identifier_quotes_apply_yn bpchar(1) NOT NULL DEFAULT 'N'::bpchar;

UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 화면' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0027';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 삭제' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0027_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 적용' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0027_02';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 등록 팝업' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0028';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 등록' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0028_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 수정 팝업' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0029';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '서버접근설정 수정' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0029_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '설정변경이력 화면' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0030';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '설정변경이력 조회' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0030_01';
UPDATE T_SYSDTL_C SET SYS_CD_NM = '설정변경이력 복원' WHERE GRP_CD = 'TC0001' AND SYS_CD = 'DX-T0030_02';




