INSERT INTO T_SYSGRP_C(GRP_CD, GRP_CD_NM, GRP_CD_EXP, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES( 'TC0037', '압축형태', '데이터전송 압축형태', 'Y', 'ADMIN', clock_timestamp(), 'ADMIN', clock_timestamp());

INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0037', 'TC003701', 'none', 'Y', 'ADMIN', CLOCK_TIMESTAMP(), 'ADMIN', CLOCK_TIMESTAMP());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0037', 'TC003702', 'gzip', 'N', 'ADMIN', CLOCK_TIMESTAMP(), 'ADMIN', CLOCK_TIMESTAMP());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0037', 'TC003703', 'snappy', 'Y', 'ADMIN', CLOCK_TIMESTAMP(), 'ADMIN', CLOCK_TIMESTAMP());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0037', 'TC003704', 'lz4', 'N', 'ADMIN', CLOCK_TIMESTAMP(), 'ADMIN', CLOCK_TIMESTAMP());
INSERT INTO T_SYSDTL_C(GRP_CD, SYS_CD, SYS_CD_NM, USE_YN, FRST_REGR_ID, FRST_REG_DTM, LST_MDFR_ID, LST_MDF_DTM ) VALUES('TC0037', 'TC003705', 'zstd', 'N', 'ADMIN', CLOCK_TIMESTAMP(), 'ADMIN', CLOCK_TIMESTAMP());
