

CREATE TABLE T_ADTCNG_I(
	ADT_CNG_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	READ_LOG_YN          VARCHAR(1) NULL,
	WRT_LOG_YN           VARCHAR(1) NULL,
	FUN_LOG_YN           VARCHAR(1) NULL,
	ROLE_LOG_YN          VARCHAR(1) NULL,
	DDL_LOG_YN           VARCHAR(1) NULL,
	MISC_LOG_YN          VARCHAR(1) NULL,
	LOG_LVL_CD           VARCHAR(20) NULL,
	LOG_CTL_VTLN_YN      VARCHAR(1) NULL,
	LOG_PRM_VTLN_YN      VARCHAR(1) NULL,
	LOG_RLT_VTLN_YN      VARCHAR(1) NULL,
	LOG_CSTM_VTLN_YN     VARCHAR(1) NULL,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);



ALTER TABLE T_ADTCNG_I ADD CONSTRAINT PK_T_ADTCNG_I
PRIMARY KEY (ADT_CNG_ID);


COMMENT ON TABLE T_ADTCNG_I IS '감사설정정보';

 COMMENT ON COLUMN T_ADTCNG_I.ADT_CNG_ID IS '감사_설정_ID';
 COMMENT ON COLUMN T_ADTCNG_I.READ_LOG_YN IS '읽기_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.WRT_LOG_YN IS '쓰기_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.FUN_LOG_YN IS '함수_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.ROLE_LOG_YN IS '롤_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.DDL_LOG_YN IS 'DDL_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.MISC_LOG_YN IS 'MISC_로그_여부';
 COMMENT ON COLUMN T_ADTCNG_I.LOG_LVL_CD IS '로그_레벨_코드';
 COMMENT ON COLUMN T_ADTCNG_I.LOG_CTL_VTLN_YN IS '로그_카탈로그_활성화_여부';
 COMMENT ON COLUMN T_ADTCNG_I.LOG_PRM_VTLN_YN IS '로그_파라미터_활성화_여부';
 COMMENT ON COLUMN T_ADTCNG_I.LOG_RLT_VTLN_YN IS '로그_관계_활성화_여부';
 COMMENT ON COLUMN T_ADTCNG_I.LOG_CSTM_VTLN_YN IS '로그_명령문_활성화_여부';
 COMMENT ON COLUMN T_ADTCNG_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_ADTCNG_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_ADTCNG_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_ADTCNG_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_ADTCNG_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_ADTCNGDB_I
(
	ADT_CNG_DB_SN        NUMERIC NOT NULL DEFAULT 1,
	ADT_CNG_ID           NUMERIC(18) NULL DEFAULT 1,
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	ADT_YN               VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);


ALTER TABLE T_ADTCNGDB_I ADD CONSTRAINT PK_T_ADTCNGDB_I
PRIMARY KEY (ADT_CNG_DB_SN);

CREATE UNIQUE INDEX UK_T_ADTCNGDB_I_01 ON T_ADTCNGDB_I
(
	ADT_CNG_ID
);

COMMENT ON TABLE T_ADTCNGDB_I IS '감사설정DB정보';

 COMMENT ON COLUMN T_ADTCNGDB_I.ADT_CNG_DB_SN IS '감사_설정_DB_일련번호';
 COMMENT ON COLUMN T_ADTCNGDB_I.ADT_CNG_ID IS '감사_설정_ID';
 COMMENT ON COLUMN T_ADTCNGDB_I.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_ADTCNGDB_I.ADT_YN IS '감사_여부';
 COMMENT ON COLUMN T_ADTCNGDB_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_ADTCNGDB_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_ADTCNGDB_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_ADTCNGDB_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_AGTCNDT_I
(
	AGT_SN            NUMERIC(18) NOT NULL DEFAULT 1,
	IPADR               VARCHAR(30) NULL,
	SOCKET_PORT	     NUMERIC(5),
	AGT_CNDT_CD          VARCHAR(20) NULL,
	STRT_DTM             TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	ISTCNF_YN            VARCHAR(1) NULL,
	AGT_VERSION          VARCHAR(10) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);


ALTER TABLE T_AGTCNDT_I ADD CONSTRAINT PK_T_AGTCNDT_I
PRIMARY KEY (AGT_SN);

COMMENT ON TABLE T_AGTCNDT_I IS '에이전트상태정보';

 COMMENT ON COLUMN T_AGTCNDT_I.AGT_SN IS '에이전트_일련번호';
 COMMENT ON COLUMN T_AGTCNDT_I.IPADR IS 'IP주소';
 COMMENT ON COLUMN T_AGTCNDT_I.SOCKET_PORT IS '소켓_포트';
 COMMENT ON COLUMN T_AGTCNDT_I.AGT_CNDT_CD IS '에이전트_상태_코드';
 COMMENT ON COLUMN T_AGTCNDT_I.STRT_DTM IS '시작_일시';
 COMMENT ON COLUMN T_AGTCNDT_I.ISTCNF_YN IS '설치확인_여부';
 COMMENT ON COLUMN T_AGTCNDT_I.AGT_VERSION IS '에이전트_버젼';
 COMMENT ON COLUMN T_AGTCNDT_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_AGTCNDT_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_AGTCNDT_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_AGTCNDT_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_BCKOBJ_L
(
	OBJ_SN               NUMERIC NOT NULL DEFAULT 1,
	BCK_WRK_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	SCM_NM               VARCHAR(50) NULL,
	OBJ_NM               VARCHAR(50) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_BCKOBJ_L_01 ON T_BCKOBJ_L
(
	BCK_WRK_ID,
	DB_ID,
	SCM_NM,
	OBJ_NM
);
ALTER TABLE T_BCKOBJ_L ADD CONSTRAINT PK_T_BCKOBJ_L
PRIMARY KEY (OBJ_SN);

COMMENT ON TABLE T_BCKOBJ_L IS '백업오브젝트내역';

 COMMENT ON COLUMN T_BCKOBJ_L.OBJ_SN IS '오브젝트_일련번호';
 COMMENT ON COLUMN T_BCKOBJ_L.BCK_WRK_ID IS '백업_작업_ID';
 COMMENT ON COLUMN T_BCKOBJ_L.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_BCKOBJ_L.SCM_NM IS '스키마_명';
 COMMENT ON COLUMN T_BCKOBJ_L.OBJ_NM IS '오브젝트_명';
 COMMENT ON COLUMN T_BCKOBJ_L.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_BCKOBJ_L.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_BCKOBJ_L.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_BCKOBJ_L.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_BCKOPT_I
(
	BCK_WRK_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	OPT_SN               NUMERIC NOT NULL DEFAULT 1,
	GRP_CD               VARCHAR(20) NOT NULL,
	OPT_CD               VARCHAR(20) NOT NULL,
	BCK_OPT_VAL          VARCHAR(50) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_BCKOPT_I ADD CONSTRAINT PK_T_BCKOPT_I
PRIMARY KEY (BCK_WRK_ID,
             OPT_SN);

CREATE UNIQUE INDEX UK_T_BCKOPT_I_01 ON T_BCKOPT_I
(
	BCK_WRK_ID,
	GRP_CD,
	OPT_CD
);

COMMENT ON TABLE T_BCKOPT_I IS '백업옵션정보';

 COMMENT ON COLUMN T_BCKOPT_I.BCK_WRK_ID IS '백업_작업_ID';
 COMMENT ON COLUMN T_BCKOPT_I.OPT_SN IS '옵션_일련번호';
 COMMENT ON COLUMN T_BCKOPT_I.GRP_CD IS '그룹_코드';
 COMMENT ON COLUMN T_BCKOPT_I.OPT_CD IS '옵션_코드';
 COMMENT ON COLUMN T_BCKOPT_I.BCK_OPT_VAL IS '백업_옵션_값';
 COMMENT ON COLUMN T_BCKOPT_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_BCKOPT_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_BCKOPT_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_BCKOPT_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_CNR_I
(
	CNR_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	CNR_NM               VARCHAR(50) NULL,
	CNR_IPADR            VARCHAR(30) NULL,
	CNR_PORTNO           NUMERIC(5) NOT NULL DEFAULT 0,
	CNR_CNN_TP_CD        VARCHAR(20) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_CNR_I_01 ON T_CNR_I
(
	CNR_NM
);
ALTER TABLE T_CNR_I ADD CONSTRAINT PK_T_CNR_I
PRIMARY KEY (CNR_ID);

COMMENT ON TABLE T_CNR_I IS '커넥터정보';

 COMMENT ON COLUMN T_CNR_I.CNR_ID IS '커넥터_ID';
 COMMENT ON COLUMN T_CNR_I.CNR_NM IS '커넥터_명';
 COMMENT ON COLUMN T_CNR_I.CNR_IPADR IS '커넥터_IP주소';
 COMMENT ON COLUMN T_CNR_I.CNR_PORTNO IS '커넥터_포트번호';
 COMMENT ON COLUMN T_CNR_I.CNR_CNN_TP_CD IS '커넥터_연결_유형_코드';
 COMMENT ON COLUMN T_CNR_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_CNR_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_CNR_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_CNR_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_DB_I
(
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	DB_NM                VARCHAR(50) NULL,
	DB_EXP               VARCHAR(500) NULL,
	USEYN                CHAR(1) NOT NULL DEFAULT 'Y',
	DB_USR_ID            VARCHAR(30) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_DB_I_01 ON T_DB_I
(
	DB_SVR_ID,
	DB_NM
);
ALTER TABLE T_DB_I ADD CONSTRAINT PK_T_DB_I
PRIMARY KEY (DB_ID);

COMMENT ON TABLE T_DB_I IS 'DB정보';

 COMMENT ON COLUMN T_DB_I.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_DB_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_DB_I.DB_NM IS 'DB_명';
 COMMENT ON COLUMN T_DB_I.DB_EXP IS 'DB_설명';
 COMMENT ON COLUMN T_DB_I.USEYN IS '사용여부';
 COMMENT ON COLUMN T_DB_I.DB_USR_ID IS 'DB_사용자_ID';
 COMMENT ON COLUMN T_DB_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_DB_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_DB_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_DB_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_DBSVR_I
(
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_NM            VARCHAR(50) NULL,
	IPADR                VARCHAR(30) NULL,
	PORTNO               NUMERIC(5) NOT NULL DEFAULT 0,
	DFT_DB_NM            VARCHAR(50) NULL,
	PGHOME_PTH           VARCHAR(500) NULL,
        PGDATA_PTH           VARCHAR(500) NULL,
	USEYN                CHAR(1) NOT NULL DEFAULT 'Y',
	SVR_SPR_USR_ID       VARCHAR(30) NOT NULL DEFAULT 1,
	SVR_SPR_SCM_PWD      VARCHAR(100) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_DBSVR_I_01 ON T_DBSVR_I
(
	DB_SVR_NM
);
ALTER TABLE T_DBSVR_I ADD CONSTRAINT PK_T_DBSVR_I
PRIMARY KEY (DB_SVR_ID);

COMMENT ON TABLE T_DBSVR_I IS 'DB서버정보';

 COMMENT ON COLUMN T_DBSVR_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_DBSVR_I.DB_SVR_NM IS 'DB_서버_명';
 COMMENT ON COLUMN T_DBSVR_I.IPADR IS 'IP주소';
 COMMENT ON COLUMN T_DBSVR_I.PORTNO IS '포트번호';
 COMMENT ON COLUMN T_DBSVR_I.DFT_DB_NM IS '디폴트_DB_명';
 COMMENT ON COLUMN T_DBSVR_I.PGHOME_PTH IS 'PGHOME_경로';
 COMMENT ON COLUMN T_DBSVR_I.PGDATA_PTH IS 'PGDATA_경로';
 COMMENT ON COLUMN T_DBSVR_I.USEYN IS '사용여부';
 COMMENT ON COLUMN T_DBSVR_I.SVR_SPR_USR_ID IS '서버_슈퍼_사용자_ID';
 COMMENT ON COLUMN T_DBSVR_I.SVR_SPR_SCM_PWD IS '서버_슈퍼_스키마_비밀번호';
 COMMENT ON COLUMN T_DBSVR_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_DBSVR_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_DBSVR_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_DBSVR_I.LST_MDF_DTM IS '최종_수정_일시';




CREATE TABLE T_DBSVRIPADR_I
(
	DB_SVR_IPADR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL,
        MASTER_GBN            CHAR(1) NOT NULL,
	IPADR                VARCHAR(30) NULL,
	PORTNO               NUMERIC(5) NOT NULL DEFAULT 0,
        DB_CNDT              CHAR(1) NOT NULL DEFAULT 'Y',
	SVR_HOST_NM          VARCHAR(200) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_DBSVRIPADR_I ADD CONSTRAINT PK_T_DBSVRIPADR_I
PRIMARY KEY (DB_SVR_IPADR_ID);

COMMENT ON TABLE T_DBSVRIPADR_I IS 'DB서버아이피주소정보';

 COMMENT ON COLUMN T_DBSVRIPADR_I.DB_SVR_IPADR_ID IS 'DB_서버_IP주소_ID';
 COMMENT ON COLUMN T_DBSVRIPADR_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_DBSVRIPADR_I.MASTER_GBN IS '마스터_구분';
 COMMENT ON COLUMN T_DBSVRIPADR_I.IPADR IS 'IP주소';
 COMMENT ON COLUMN T_DBSVRIPADR_I.PORTNO IS '포트번호';
 COMMENT ON COLUMN T_DBSVRIPADR_I.DB_CNDT IS 'DB_상태';
 COMMENT ON COLUMN T_DBSVRIPADR_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_DBSVRIPADR_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_DBSVRIPADR_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_DBSVRIPADR_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_MNU_I
(
	MNU_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	MNU_CD               VARCHAR(50) NULL,
	MNU_NM               VARCHAR(50) NULL,
	HGR_MNU_ID           VARCHAR(30) NOT NULL DEFAULT 1,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_MNU_I ADD CONSTRAINT PK_T_MNU_I
PRIMARY KEY (MNU_ID);

COMMENT ON TABLE T_MNU_I IS '메뉴정보';

 COMMENT ON COLUMN T_MNU_I.MNU_ID IS '메뉴_ID';
 COMMENT ON COLUMN T_MNU_I.MNU_NM IS '메뉴_명';
 COMMENT ON COLUMN T_MNU_I.HGR_MNU_ID IS '상위_메뉴_ID';
 COMMENT ON COLUMN T_MNU_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_MNU_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_MNU_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_MNU_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_SCD_D
(
	SCD_DTL_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	SCD_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	WRK_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	EXE_ORD              INTEGER NOT NULL DEFAULT 0,
	NXT_EXE_YN           VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
CREATE UNIQUE INDEX UK_T_SCD_D_01 ON T_SCD_D
(
	SCD_ID,
	WRK_ID
);

ALTER TABLE T_SCD_D ADD CONSTRAINT PK_T_SCD_D
PRIMARY KEY (SCD_DTL_ID);

COMMENT ON TABLE T_SCD_D IS '스케줄상세';

 COMMENT ON COLUMN T_SCD_D.SCD_DTL_ID IS '스케줄_상세_ID';
 COMMENT ON COLUMN T_SCD_D.SCD_ID IS '스케줄_ID';
 COMMENT ON COLUMN T_SCD_D.WRK_ID IS '작업_ID';
 COMMENT ON COLUMN T_SCD_D.EXE_ORD IS '실행_순서';
 COMMENT ON COLUMN T_SCD_D.NXT_EXE_YN IS '다음_실행_여부';
 COMMENT ON COLUMN T_SCD_D.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_SCD_D.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_SCD_D.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SCD_D.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_SCD_M
(
	SCD_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	SCD_NM               VARCHAR(50) NULL,
	SCD_EXP              VARCHAR(200) NULL,
	SCD_CNDT	     VARCHAR(20) NULL,
	EXE_PERD_CD          VARCHAR(20) NULL,
	EXE_DT               VARCHAR(8) NULL,
	EXE_MONTH            VARCHAR(2) NULL,
	EXE_DAY              VARCHAR(3) NULL,
	EXE_HMS              VARCHAR(6) NULL,
	PREV_EXE_DTM         TIMESTAMP NULL,
	NXT_EXE_DTM          TIMESTAMP NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_SCD_M_01 ON T_SCD_M
(
	SCD_NM
);
ALTER TABLE T_SCD_M ADD CONSTRAINT PK_T_SCD_M
PRIMARY KEY (SCD_ID);

COMMENT ON TABLE T_SCD_M IS '스케줄기본';

 COMMENT ON COLUMN T_SCD_M.SCD_ID IS '스케줄_ID';
 COMMENT ON COLUMN T_SCD_M.SCD_NM IS '스케줄_명';
 COMMENT ON COLUMN T_SCD_M.SCD_EXP IS '스케줄_설명';
 COMMENT ON COLUMN T_SCD_M.SCD_CNDT IS '스케줄_상태';
 COMMENT ON COLUMN T_SCD_M.EXE_PERD_CD IS '실행_주기_코드';
 COMMENT ON COLUMN T_SCD_M.EXE_DT IS '실행_일자';
 COMMENT ON COLUMN T_SCD_M.EXE_MONTH IS '실행_월';
 COMMENT ON COLUMN T_SCD_M.EXE_DAY IS '실행_일';
 COMMENT ON COLUMN T_SCD_M.EXE_HMS IS '실행_시분초';
 COMMENT ON COLUMN T_SCD_M.PREV_EXE_DTM IS '이전_실행_일시';
 COMMENT ON COLUMN T_SCD_M.NXT_EXE_DTM IS '다음_실행_일시';
 COMMENT ON COLUMN T_SCD_M.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_SCD_M.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_SCD_M.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SCD_M.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_SVRACSCNTR_I
(
	SVR_ACS_CNTR_ID      NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
        DTB                  VARCHAR(200) NULL,
	PRMS_IPADR           VARCHAR(30) NULL,
	PRMS_IPMASKADR       VARCHAR(30) NULL,
	PRMS_USR_ID          VARCHAR(30) NOT NULL DEFAULT 1,
	PRMS_SEQ	     NUMERIC(18) NOT NULL DEFAULT 1,
	PRMS_SET	     VARCHAR(1) NULL,
	CTF_MTH_NM           VARCHAR(50) NULL,
	CTF_TP_NM            VARCHAR(50) NULL,
	OPT_NM               VARCHAR(50) NULL,
	CMD_CNTS             VARCHAR(400) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_SVRACSCNTR_I_01 ON T_SVRACSCNTR_I
(
	DB_SVR_ID,
	PRMS_IPADR,
	PRMS_USR_ID,
	PRMS_SEQ
);
ALTER TABLE T_SVRACSCNTR_I ADD CONSTRAINT PK_T_SVRACSCNTR_I
PRIMARY KEY (SVR_ACS_CNTR_ID);

COMMENT ON TABLE T_SVRACSCNTR_I IS '서버접근제어정보';

 COMMENT ON COLUMN T_SVRACSCNTR_I.SVR_ACS_CNTR_ID IS '서버_접근_제어_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_I.DTB IS 'DATABASE';
 COMMENT ON COLUMN T_SVRACSCNTR_I.PRMS_IPADR IS '허용_IP주소';
 COMMENT ON COLUMN T_SVRACSCNTR_I.PRMS_IPMASKADR IS '허용_IPMASK주소';
 COMMENT ON COLUMN T_SVRACSCNTR_I.PRMS_USR_ID IS '허용_사용자_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_I.PRMS_SEQ IS '허용순번';
 COMMENT ON COLUMN T_SVRACSCNTR_I.PRMS_SET IS '인증사용여부';
 COMMENT ON COLUMN T_SVRACSCNTR_I.CTF_MTH_NM IS '인증_방법_명';
 COMMENT ON COLUMN T_SVRACSCNTR_I.CTF_TP_NM IS '인증_유형_명';
 COMMENT ON COLUMN T_SVRACSCNTR_I.OPT_NM IS '옵션_명';
 COMMENT ON COLUMN T_SVRACSCNTR_I.CMD_CNTS IS '명령어_내용';
 COMMENT ON COLUMN T_SVRACSCNTR_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_SVRACSCNTR_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_SVRACSCNTR_HIS_I
(
	SVR_ACS_CNTR_HIS_ID      NUMERIC(18) NOT NULL DEFAULT 1,
	HIS_GRP_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	SVR_ACS_CNTR_ID      NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
        DTB                  VARCHAR(200) NULL,
	PRMS_IPADR           VARCHAR(30) NULL,
	PRMS_IPMASKADR       VARCHAR(30) NULL,
	PRMS_USR_ID          VARCHAR(30) NOT NULL DEFAULT 1,
	PRMS_SEQ	     NUMERIC(18) NOT NULL DEFAULT 1,
	PRMS_SET	     VARCHAR(1) NULL,
	CTF_MTH_NM           VARCHAR(50) NULL,
	CTF_TP_NM            VARCHAR(50) NULL,
	OPT_NM               VARCHAR(50) NULL,
	CMD_CNTS             VARCHAR(400) NULL,
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);


ALTER TABLE T_SVRACSCNTR_HIS_I ADD CONSTRAINT PK_T_SVRACSCNTR_HIS_I
PRIMARY KEY (SVR_ACS_CNTR_HIS_ID);

COMMENT ON TABLE T_SVRACSCNTR_HIS_I IS '서버접근제어_이력_정보';

 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.SVR_ACS_CNTR_HIS_ID IS '서버_접근_제어_이력_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.HIS_GRP_ID IS '이력_그룹_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.SVR_ACS_CNTR_ID IS '서버_접근_제어_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.DTB IS 'DATABASE';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.PRMS_IPADR IS '허용_IP주소';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.PRMS_IPMASKADR IS '허용_IPMASK주소';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.PRMS_USR_ID IS '허용_사용자_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.PRMS_SEQ IS '허용순번';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.PRMS_SET IS '인증사용여부';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.CTF_MTH_NM IS '인증_방법_명';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.CTF_TP_NM IS '인증_유형_명';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.OPT_NM IS '옵션_명';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.CMD_CNTS IS '명령어_내용';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SVRACSCNTR_HIS_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_SYSDTL_C
(
	GRP_CD               VARCHAR(20) NOT NULL,
	SYS_CD               VARCHAR(20) NOT NULL,
	SYS_CD_NM            VARCHAR(50) NULL,
	USE_YN               VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_SYSDTL_C ADD CONSTRAINT PK_T_SYSDTL_C
PRIMARY KEY (GRP_CD,
             SYS_CD);

COMMENT ON TABLE T_SYSDTL_C IS '시스템상세코드';

 COMMENT ON COLUMN T_SYSDTL_C.GRP_CD IS '그룹_코드';
 COMMENT ON COLUMN T_SYSDTL_C.SYS_CD IS '시스템_코드';
 COMMENT ON COLUMN T_SYSDTL_C.SYS_CD_NM IS '시스템_코드_명';
 COMMENT ON COLUMN T_SYSDTL_C.USE_YN IS '사용_여부';
 COMMENT ON COLUMN T_SYSDTL_C.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_SYSDTL_C.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_SYSDTL_C.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SYSDTL_C.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_SYSGRP_C
(
	GRP_CD               VARCHAR(20) NOT NULL,
	GRP_CD_NM            VARCHAR(50) NULL,
	GRP_CD_EXP           VARCHAR(200) NULL,
	USE_YN               VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_SYSGRP_C ADD CONSTRAINT PK_T_SYSGRP_C
PRIMARY KEY (GRP_CD);

COMMENT ON TABLE T_SYSGRP_C IS '시스템그룹코드';

 COMMENT ON COLUMN T_SYSGRP_C.GRP_CD IS '그룹_코드';
 COMMENT ON COLUMN T_SYSGRP_C.GRP_CD_NM IS '그룹_코드_명';
 COMMENT ON COLUMN T_SYSGRP_C.GRP_CD_EXP IS '그룹_코드_설명';
 COMMENT ON COLUMN T_SYSGRP_C.USE_YN IS '사용_여부';
 COMMENT ON COLUMN T_SYSGRP_C.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_SYSGRP_C.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_SYSGRP_C.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_SYSGRP_C.LST_MDF_DTM IS '최종_수정_일시';

;

 CREATE TABLE T_SYSWRK_G
(
	WRK_SN               NUMERIC NOT NULL DEFAULT 1,
	USR_ID               VARCHAR(30) NOT NULL,
	MNU_ID               NUMERIC(18) NULL DEFAULT 1,
	EXE_DTL_CD           VARCHAR(20) NULL,
	EXEDTM               TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
    LGI_IPADR            VARCHAR(30) NULL
);

ALTER TABLE T_SYSWRK_G ADD CONSTRAINT PK_T_SYSWRK_G
PRIMARY KEY (WRK_SN);

COMMENT ON TABLE T_SYSWRK_G IS '시스템작업로그';

 COMMENT ON COLUMN T_SYSWRK_G.WRK_SN IS '작업_일련번호';
 COMMENT ON COLUMN T_SYSWRK_G.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_SYSWRK_G.MNU_ID IS '메뉴_ID';
 COMMENT ON COLUMN T_SYSWRK_G.EXE_DTL_CD IS '실행_상세_코드';
 COMMENT ON COLUMN T_SYSWRK_G.EXEDTM IS '실행일시';
 COMMENT ON COLUMN T_SYSWRK_G.LGI_IPADR IS '로그인_IP주소';


CREATE TABLE T_TRFCNG_I
(
	TRF_CNG_ID              NUMERIC(18) NOT NULL DEFAULT 1,
	KAFKA_BROKER_IP         VARCHAR(50) NULL,
	KAFKA_BROKER_PORT       NUMERIC(5) NOT NULL DEFAULT 0,
	SCHEMA_REGISTRY_IP      VARCHAR(50) NULL,
	SCHEMA_REGISTRY_PORT    NUMERIC(5) NOT NULL DEFAULT 0,
	ZOOKEEPER_IP            VARCHAR(50) NULL,
	ZOOKEEPER_PORT          NUMERIC(5) NOT NULL DEFAULT 0,
	BW_HOME                 VARCHAR(500) NULL,
	TENG_IP                 VARCHAR(30) NULL,
	TENG_PORT               NUMERIC(5) NOT NULL DEFAULT 0,
	FRST_REGR_ID            VARCHAR(30) NULL,
	FRST_REG_DTM            TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID             VARCHAR(30) NULL,
	LST_MDF_DTM             TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);


ALTER TABLE T_TRFCNG_I ADD CONSTRAINT PK_T_TRFCNG_I
PRIMARY KEY (TRF_CNG_ID);

COMMENT ON TABLE T_TRFCNG_I IS '전송설정정보';

 COMMENT ON COLUMN T_TRFCNG_I.TRF_CNG_ID IS '전송_설정_ID';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_IP IS 'KAFKA_BROKER_IP';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_PORT IS 'KAFKA_BROKER_PORT';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_IP IS 'SCHEMA_REGISTRY_IP';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_PORT IS 'SCHEMA_REGISTRY_PORT';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_IP IS 'ZOOKEEPER_IP';
 COMMENT ON COLUMN T_TRFCNG_I.KAFKA_BROKER_PORT IS 'ZOOKEEPER_PORT';
 COMMENT ON COLUMN T_TRFCNG_I.BW_HOME IS 'BottledWater HOME';
 COMMENT ON COLUMN T_TRFCNG_I.TENG_IP IS 'Agent IP';
 COMMENT ON COLUMN T_TRFCNG_I.TENG_PORT IS 'Agent Port';

 COMMENT ON COLUMN T_TRFCNG_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_TRFCNG_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_TRFCNG_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_TRFCNG_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_TRFMPPTB_L
(
	TRF_TB_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	TRF_TRG_MPP_ID       NUMERIC(18) NOT NULL DEFAULT 1,
	SCM_NM               VARCHAR(50) NULL,
	TB_ENGL_NM           VARCHAR(50) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_TRFMPPTB_L_01 ON T_TRFMPPTB_L
(
	SCM_NM,
	TB_ENGL_NM,
	TRF_TRG_MPP_ID
);

ALTER TABLE T_TRFMPPTB_L ADD CONSTRAINT PK_T_TRFMPPTB_L
PRIMARY KEY (TRF_TB_ID);

COMMENT ON TABLE T_TRFMPPTB_L IS '전송매핑테이블내역';

 COMMENT ON COLUMN T_TRFMPPTB_L.TRF_TB_ID IS '전송_테이블_ID';
 COMMENT ON COLUMN T_TRFMPPTB_L.TRF_TRG_MPP_ID IS '전송_대상_매핑_ID';
 COMMENT ON COLUMN T_TRFMPPTB_L.SCM_NM IS '스키마_명';
 COMMENT ON COLUMN T_TRFMPPTB_L.TB_ENGL_NM IS '테이블_영문_명';
 COMMENT ON COLUMN T_TRFMPPTB_L.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_TRFMPPTB_L.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_TRFMPPTB_L.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_TRFMPPTB_L.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_TRFTRGCNG_I
(
	TRF_TRG_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	TRF_TRG_CNN_NM       VARCHAR(50) NULL,
	TRF_TRG_URL          VARCHAR(200) NULL,
	CONNECTOR_CLASS	     VARCHAR(300) NULL,
	TASK_MAX	     NUMERIC(5) NOT NULL DEFAULT 0,
	HADOOP_CONF_DIR	     VARCHAR(300) NULL,
	HADOOP_HOME	     VARCHAR(300) NULL,
	FLUSH_SIZE	     NUMERIC(5) NOT NULL DEFAULT 0,
	ROTATE_INTERVAL_MS   NUMERIC(5) NOT NULL DEFAULT 0,
	CNR_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	BW_PID               NUMERIC(5) NOT NULL DEFAULT 0,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_TRFTRGCNG_I_01 ON T_TRFTRGCNG_I
(
	TRF_TRG_CNN_NM
);
ALTER TABLE T_TRFTRGCNG_I ADD CONSTRAINT PK_T_TRFTRGCNG_I
PRIMARY KEY (TRF_TRG_ID);

COMMENT ON TABLE T_TRFTRGCNG_I IS '전송대상설정정보';

 COMMENT ON COLUMN T_TRFTRGCNG_I.TRF_TRG_ID IS '전송_대상_ID';
 COMMENT ON COLUMN T_TRFTRGCNG_I.TRF_TRG_CNN_NM IS '전송_대상_연결_명';
 COMMENT ON COLUMN T_TRFTRGCNG_I.TRF_TRG_URL IS '전송_대상_URL';
 COMMENT ON COLUMN T_TRFTRGCNG_I.CNR_ID IS '커넥터_ID';
 COMMENT ON COLUMN T_TRFTRGCNG_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_TRFTRGCNG_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_TRFTRGCNG_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_TRFTRGCNG_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_TRFTRGMPP_R
(
	TRF_TRG_MPP_ID       NUMERIC(18) NOT NULL DEFAULT 1,
	TRF_TRG_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	CNR_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_TRFTRGMPP_R_01 ON T_TRFTRGMPP_R
(
	TRF_TRG_ID,
	DB_ID,
	CNR_ID
);

ALTER TABLE T_TRFTRGMPP_R ADD CONSTRAINT PK_T_TRFTRGMPP_R
PRIMARY KEY (TRF_TRG_MPP_ID);

COMMENT ON TABLE T_TRFTRGMPP_R IS '전송대상매핑관계';

 COMMENT ON COLUMN T_TRFTRGMPP_R.TRF_TRG_MPP_ID IS '전송_대상_매핑_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.TRF_TRG_ID IS '전송_대상_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.CNR_ID IS '커넥터_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_TRFTRGMPP_R.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_TRFTRGMPP_R.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_USR_I
(
	USR_ID               VARCHAR(30) NOT NULL,
	USR_NM               VARCHAR(50) NULL,
	PWD                  VARCHAR(100) NULL,
	BLN_NM               VARCHAR(50) NULL,
	DEPT_NM              VARCHAR(50) NULL,
	RSP_BSN_NM           VARCHAR(50) NULL,
	PST_NM               VARCHAR(50) NULL,
	AUT_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	CPN                  VARCHAR(20) NULL,
	USR_EXPR_DT          VARCHAR(8) NULL,
	USE_YN               VARCHAR(1) NULL,
	ENCP_USE_YN          VARCHAR(1) NOT NULL DEFAULT 'N' ,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_USR_I ADD CONSTRAINT PK_T_USR_I
PRIMARY KEY (USR_ID);

COMMENT ON TABLE T_USR_I IS '사용자정보';

 COMMENT ON COLUMN T_USR_I.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_USR_I.USR_NM IS '사용자_명';
 COMMENT ON COLUMN T_USR_I.PWD IS '비밀번호';
 COMMENT ON COLUMN T_USR_I.BLN_NM IS '소속_명';
 COMMENT ON COLUMN T_USR_I.DEPT_NM IS '부서_명';
 COMMENT ON COLUMN T_USR_I.RSP_BSN_NM IS '담당_업무_명';
 COMMENT ON COLUMN T_USR_I.PST_NM IS '직급_명';
 COMMENT ON COLUMN T_USR_I.AUT_ID IS '권한_ID';
 COMMENT ON COLUMN T_USR_I.CPN IS    '휴대폰번호';
 COMMENT ON COLUMN T_USR_I.USR_EXPR_DT IS '사용자_만료_일자';
 COMMENT ON COLUMN T_USR_I.USE_YN IS '사용_여부';
 COMMENT ON COLUMN T_USR_I.ENCP_USE_YN IS '암호화_사용_여부';
 COMMENT ON COLUMN T_USR_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_USR_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_USR_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_USR_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_USRDBAUT_I
(
	USR_DB_AUT_ID        NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	USR_ID               VARCHAR(30) NOT NULL,
	AUT_YN               VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_USRDBAUT_I_01 ON T_USRDBAUT_I
(
	DB_SVR_ID,
	DB_ID,
	USR_ID
);

ALTER TABLE T_USRDBAUT_I ADD CONSTRAINT PK_T_USRDBAUT_I
PRIMARY KEY (USR_DB_AUT_ID);

COMMENT ON TABLE T_USRDBAUT_I IS '사용자DB권한정보';

 COMMENT ON COLUMN T_USRDBAUT_I.USR_DB_AUT_ID IS '사용자_DB_권한_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.AUT_YN IS '권한_여부';
 COMMENT ON COLUMN T_USRDBAUT_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_USRDBAUT_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_USRDBAUT_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_USRDBSVRAUT_I
(
	USR_DB_SVR_AUT_ID    NUMERIC(18) NOT NULL DEFAULT 1,
	USR_ID               VARCHAR(30) NOT NULL,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	BCK_CNG_AUT_YN       VARCHAR(1) NULL,
	BCK_HIST_AUT_YN      VARCHAR(1) NULL,
	ACS_CNTR_AUT_YN      VARCHAR(1) NULL,
	ADT_CNG_AUT_YN       VARCHAR(1) NULL,
	ADT_HIST_AUT_YN      VARCHAR(1) NULL,
	BCK_SCDR_AUT_YN      VARCHAR(1) NULL,
	POLICY_CHANGE_HIS_AUT_YN      VARCHAR(1) NULL,
	SCRIPT_CNG_AUT_YN    VARCHAR(1) NULL,
	SCRIPT_HIS_AUT_YN    VARCHAR(1) NULL,
	EMERGENCY_RESTORE_AUT_YN    VARCHAR(1) NULL,
	POINT_RESTORE_AUT_YN    VARCHAR(1) NULL,
	DUMP_RESTORE_AUT_YN    VARCHAR(1) NULL,
	RESTORE_HIS_AUT_YN    VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_USRDBSVRAUT_I_01 ON T_USRDBSVRAUT_I
(
	USR_ID,
	DB_SVR_ID
);

ALTER TABLE T_USRDBSVRAUT_I ADD CONSTRAINT PK_T_USRDBSVRAUT_I
PRIMARY KEY (USR_DB_SVR_AUT_ID);

COMMENT ON TABLE T_USRDBSVRAUT_I IS '사용자DB서버권한정보';

 COMMENT ON COLUMN T_USRDBSVRAUT_I.USR_DB_SVR_AUT_ID IS '사용자_DB_서버_권한_ID';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.BCK_CNG_AUT_YN IS '백업_설정_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.BCK_HIST_AUT_YN IS '백업_이력_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.ACS_CNTR_AUT_YN IS '접근_제어_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.ADT_CNG_AUT_YN IS '감사_설정_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.ADT_HIST_AUT_YN IS '감사_이력_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.BCK_SCDR_AUT_YN IS '백업_스케줄러_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.POLICY_CHANGE_HIS_AUT_YN IS '정책_변경_이력_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.SCRIPT_CNG_AUT_YN IS '스크립트_설정_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.SCRIPT_HIS_AUT_YN IS '스크립트_이력_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.EMERGENCY_RESTORE_AUT_YN IS '긴급_복원_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.POINT_RESTORE_AUT_YN IS '시점_복원_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.DUMP_RESTORE_AUT_YN IS '덤프_복원_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.RESTORE_HIS_AUT_YN IS '복원_이력_권한_여부';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_USRDBSVRAUT_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_USRLGI_H
(
	LGI_CRRNO            NUMERIC NOT NULL DEFAULT 1,
	USR_ID               VARCHAR(30) NOT NULL,
	LGI_DTM              TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LOG_OUT_DTM          TIMESTAMP NULL,
	USR_NM               VARCHAR(50) NULL,
	LGI_IPADR            VARCHAR(30) NULL,
	BLN_NM               VARCHAR(50) NULL,
	DEPT_NM              VARCHAR(50) NULL,
	RSP_BSN_NM           VARCHAR(50) NULL,
	PST_NM               VARCHAR(50) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_USRLGI_H_01 ON T_USRLGI_H
(
	USR_ID,
	LGI_DTM
);

ALTER TABLE T_USRLGI_H ADD CONSTRAINT PK_T_USRLGI_H
PRIMARY KEY (LGI_CRRNO);

COMMENT ON TABLE T_USRLGI_H IS '사용자로그인이력';

 COMMENT ON COLUMN T_USRLGI_H.LGI_CRRNO IS '로그인_이력번호';
 COMMENT ON COLUMN T_USRLGI_H.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_USRLGI_H.LGI_DTM IS '로그인_일시';
 COMMENT ON COLUMN T_USRLGI_H.LOG_OUT_DTM IS '로그_아웃_일시';
 COMMENT ON COLUMN T_USRLGI_H.USR_NM IS '사용자_명';
 COMMENT ON COLUMN T_USRLGI_H.LGI_IPADR IS '로그인_IP주소';
 COMMENT ON COLUMN T_USRLGI_H.BLN_NM IS '소속_명';
 COMMENT ON COLUMN T_USRLGI_H.DEPT_NM IS '부서_명';
 COMMENT ON COLUMN T_USRLGI_H.RSP_BSN_NM IS '담당_업무_명';
 COMMENT ON COLUMN T_USRLGI_H.PST_NM IS '직급_명';
 COMMENT ON COLUMN T_USRLGI_H.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_USRLGI_H.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_USRLGI_H.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_USRLGI_H.LST_MDF_DTM IS '최종_수정_일시';




CREATE TABLE T_USRMNUAUT_I
(
	USR_MNU_AUT_ID       NUMERIC(18) NOT NULL DEFAULT 1,
	USR_ID               VARCHAR(30) NOT NULL,
	MNU_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	READ_AUT_YN          VARCHAR(1) NULL,
	WRT_AUT_YN           VARCHAR(1) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_USRMNUAUT_I_01 ON T_USRMNUAUT_I
(
	USR_ID,
	MNU_ID
);
ALTER TABLE T_USRMNUAUT_I ADD CONSTRAINT PK_T_USRMNUAUT_I
PRIMARY KEY (USR_MNU_AUT_ID);

COMMENT ON TABLE T_USRMNUAUT_I IS '사용자메뉴권한정보';

 COMMENT ON COLUMN T_USRMNUAUT_I.USR_MNU_AUT_ID IS '사용자_메뉴_권한_ID';
 COMMENT ON COLUMN T_USRMNUAUT_I.USR_ID IS '사용자_ID';
 COMMENT ON COLUMN T_USRMNUAUT_I.MNU_ID IS '메뉴_ID';
 COMMENT ON COLUMN T_USRMNUAUT_I.READ_AUT_YN IS '읽기_권한_여부';
 COMMENT ON COLUMN T_USRMNUAUT_I.WRT_AUT_YN IS '쓰기_권한_여부';
 COMMENT ON COLUMN T_USRMNUAUT_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_USRMNUAUT_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_USRMNUAUT_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_USRMNUAUT_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_WRKCNG_I
(
	WRK_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	BSN_DSCD             VARCHAR(8) NULL,
	WRK_NM               VARCHAR(50) NULL,
	WRK_EXP              VARCHAR(200) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_WRKCNG_I_01 ON T_WRKCNG_I
(
	BSN_DSCD,
	WRK_NM
);

ALTER TABLE T_WRKCNG_I ADD CONSTRAINT PK_T_WRKCNG_I
PRIMARY KEY (WRK_ID);

COMMENT ON TABLE T_WRKCNG_I IS '작업설정정보';
 COMMENT ON COLUMN T_WRKCNG_I.WRK_ID IS '작업_ID';
 COMMENT ON COLUMN T_WRKCNG_I.WRK_NM IS '작업_명';
 COMMENT ON COLUMN T_WRKCNG_I.WRK_EXP IS '작업_설명';

 COMMENT ON COLUMN T_WRKCNG_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_WRKCNG_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_WRKCNG_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_WRKCNG_I.LST_MDF_DTM IS '최종_수정_일시';



CREATE TABLE T_BCK_WRKCNG_I
(
	BCK_WRK_ID           NUMERIC(18) NOT NULL DEFAULT 1,
	WRK_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	DB_ID                NUMERIC(18) NOT NULL DEFAULT 1,
	BCK_BSN_DSCD         VARCHAR(8) NULL,
	BCK_FILENM	     VARCHAR(200) NULL,
	BCK_OPT_CD           VARCHAR(20) NULL,
	BCK_MTN_ECNT         BIGINT NOT NULL DEFAULT 0,
	CPS_YN               VARCHAR(1) NULL,
	LOG_FILE_BCK_YN      VARCHAR(1) NULL,
	LOG_FILE_STG_DCNT    BIGINT NOT NULL DEFAULT 0,
	LOG_FILE_MTN_ECNT    BIGINT NOT NULL DEFAULT 0,
	CPRT                 FLOAT NOT NULL DEFAULT 0,
	SAVE_PTH             VARCHAR(200) NULL,
	FILE_FMT_CD          VARCHAR(20) NULL,
	FILE_STG_DCNT        BIGINT NOT NULL DEFAULT 0,
	ENCD_MTH_NM          VARCHAR(50) NULL,
	USR_ROLE_NM          VARCHAR(50) NULL,
	DATA_PTH             VARCHAR(300) NULL,
    BCK_PTH              VARCHAR(300) NULL,
	ACV_FILE_STGDT       BIGINT NOT NULL DEFAULT 0,
    ACV_FILE_MTNCNT      BIGINT NOT NULL DEFAULT 0,
	LOG_FILE_PTH         VARCHAR(300) NULL,
	EXE_CMD               TEXT NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_BCK_WRKCNG_I_01 ON T_BCK_WRKCNG_I
(
	WRK_ID,
	DB_SVR_ID,
	DB_ID,
	BCK_BSN_DSCD
);

ALTER TABLE T_BCK_WRKCNG_I ADD CONSTRAINT PK_T_BCK_WRKCNG_I
PRIMARY KEY (BCK_WRK_ID);

COMMENT ON TABLE T_BCK_WRKCNG_I IS '백업작업설정정보';

 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_WRK_ID IS '백업_작업_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.WRK_ID IS '작업_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_BSN_DSCD IS '백업_업무_구분코드';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_FILENM IS '백업_파일명';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_OPT_CD IS '백업_옵션_코드';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_MTN_ECNT IS '백업_유지_개수';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.CPS_YN IS '압축_여부';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.LOG_FILE_BCK_YN IS '로그_파일_백업_여부';

 COMMENT ON COLUMN T_BCK_WRKCNG_I.LOG_FILE_STG_DCNT IS '로그_파일_보관_일수';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.LOG_FILE_MTN_ECNT IS '로그_파일_유지_개수';

 COMMENT ON COLUMN T_BCK_WRKCNG_I.CPRT IS '압축률';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.SAVE_PTH IS '저장_경로';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.FILE_FMT_CD IS '파일_포맷_코드';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.FILE_STG_DCNT IS '파일_보관_일수';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.ENCD_MTH_NM IS '인코딩_방법_명';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.USR_ROLE_NM IS '사용자_롤_명';

 COMMENT ON COLUMN T_BCK_WRKCNG_I.DATA_PTH IS '데이터_경로';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.BCK_PTH IS '백업_경로';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.ACV_FILE_STGDT IS '아카이브_파일_보관일수';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.ACV_FILE_MTNCNT IS '아카이브_파일_유지갯수';

 COMMENT ON COLUMN T_BCK_WRKCNG_I.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_BCK_WRKCNG_I.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_WRKEXE_G
(
	EXE_SN               NUMERIC NOT NULL DEFAULT 1,
	SCD_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	WRK_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	WRK_STRT_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	WRK_END_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	EXE_RSLT_CD          VARCHAR(20) NULL,
	BCK_OPT_CD           VARCHAR(20) NULL,
	TLI                  BIGINT NOT NULL DEFAULT 0,
	FILE_SZ              NUMERIC(18) NOT NULL DEFAULT 0,
	DB_ID                NUMERIC(18) NOT NULL,
	BCK_FILE_PTH         VARCHAR(200) NULL,
	BCK_FILENM           VARCHAR(200) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	RSLT_MSG             VARCHAR(1000),
        EXE_GRP_SN           NUMERIC(18) NOT NULL DEFAULT 0,
	SCD_NM               VARCHAR(50) NULL,
	WRK_NM               VARCHAR(50) NULL,
	DB_SVR_IPADR_ID      NUMERIC(18) NOT NULL DEFAULT 0,
	FIX_RSLTCD           VARCHAR(20) NULL,
        FIX_RSLT_MSG         VARCHAR(1000) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);

CREATE UNIQUE INDEX UK_T_WRKEXE_G_01 ON T_WRKEXE_G
(
	SCD_ID,
	WRK_ID,
	DB_SVR_IPADR_ID,
	WRK_STRT_DTM
);

ALTER TABLE T_WRKEXE_G ADD CONSTRAINT PK_T_WRKEXE_G
PRIMARY KEY (EXE_SN);


COMMENT ON TABLE T_WRKEXE_G IS '작업실행로그';

 COMMENT ON COLUMN T_WRKEXE_G.EXE_SN IS '실행_일련번호';
 COMMENT ON COLUMN T_WRKEXE_G.SCD_ID IS '스케줄_ID';
 COMMENT ON COLUMN T_WRKEXE_G.WRK_ID IS '작업_ID';
 COMMENT ON COLUMN T_WRKEXE_G.WRK_STRT_DTM IS '작업_시작_일시';
 COMMENT ON COLUMN T_WRKEXE_G.WRK_END_DTM IS '작업_종료_일시';
 COMMENT ON COLUMN T_WRKEXE_G.EXE_RSLT_CD IS '실행_결과_코드';
 COMMENT ON COLUMN T_WRKEXE_G.BCK_OPT_CD IS '백업_옵션_코드';
 COMMENT ON COLUMN T_WRKEXE_G.TLI IS 'TLI';
 COMMENT ON COLUMN T_WRKEXE_G.FILE_SZ IS '파일_사이즈';
 COMMENT ON COLUMN T_WRKEXE_G.DB_ID IS 'DB_ID';
 COMMENT ON COLUMN T_WRKEXE_G.BCK_FILE_PTH IS '백업_파일_경로';
 COMMENT ON COLUMN T_WRKEXE_G.BCK_FILENM IS '백업_파일명';
 COMMENT ON COLUMN T_WRKEXE_G.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_WRKEXE_G.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_WRKEXE_G.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_WRKEXE_G.RSLT_MSG IS '결과_메시지';
 COMMENT ON COLUMN T_WRKEXE_G.EXE_GRP_SN IS '실행_그룹_일련번호';
 COMMENT ON COLUMN T_WRKEXE_G.SCD_NM IS '스케줄_명';
 COMMENT ON COLUMN T_WRKEXE_G.WRK_NM IS '작업_명';
 COMMENT ON COLUMN T_WRKEXE_G.DB_SVR_IPADR_ID IS 'DB_서버_IP주소_ID';
 COMMENT ON COLUMN T_WRKEXE_G.FIX_RSLTCD IS '조치_결과코드';
 COMMENT ON COLUMN T_WRKEXE_G.FIX_RSLT_MSG IS '조치_결과_메시지';
 COMMENT ON COLUMN T_WRKEXE_G.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_WRKOPTDTL_C
(
	GRP_CD               VARCHAR(20) NOT NULL,
	OPT_CD               VARCHAR(20) NOT NULL,
	OPT_CD_NM            VARCHAR(50) NULL,
	DFT_CD_VAL           VARCHAR(50) NULL,
	EXPS_ORD             INTEGER NOT NULL DEFAULT 0,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_WRKOPTDTL_C ADD CONSTRAINT PK_T_WRKOPTDTL_C
PRIMARY KEY (GRP_CD,
             OPT_CD);

COMMENT ON TABLE T_WRKOPTDTL_C IS '작업옵션상세코드';

 COMMENT ON COLUMN T_WRKOPTDTL_C.GRP_CD IS '그룹_코드';
 COMMENT ON COLUMN T_WRKOPTDTL_C.OPT_CD IS '옵션_코드';
 COMMENT ON COLUMN T_WRKOPTDTL_C.OPT_CD_NM IS '옵션_코드_명';
 COMMENT ON COLUMN T_WRKOPTDTL_C.DFT_CD_VAL IS '디폴트_코드_값';
 COMMENT ON COLUMN T_WRKOPTDTL_C.EXPS_ORD IS '표시_순서';
 COMMENT ON COLUMN T_WRKOPTDTL_C.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_WRKOPTDTL_C.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_WRKOPTDTL_C.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_WRKOPTDTL_C.LST_MDF_DTM IS '최종_수정_일시';


CREATE TABLE T_WRKOPTGRP_C
(
	GRP_CD               VARCHAR(20) NOT NULL,
	GRP_CD_NM            VARCHAR(50) NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_WRKOPTGRP_C ADD CONSTRAINT PK_T_WRKOPTGRP_C
PRIMARY KEY (GRP_CD);

COMMENT ON TABLE T_WRKOPTGRP_C IS '작업옵션그룹코드';

 COMMENT ON COLUMN T_WRKOPTGRP_C.GRP_CD IS '그룹_코드';
 COMMENT ON COLUMN T_WRKOPTGRP_C.GRP_CD_NM IS '그룹_코드_명';
 COMMENT ON COLUMN T_WRKOPTGRP_C.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_WRKOPTGRP_C.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_WRKOPTGRP_C.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_WRKOPTGRP_C.LST_MDF_DTM IS '최종_수정_일시';


 CREATE TABLE T_RMAN_RESTORE
(
	RESTORE_SN         NUMERIC NOT NULL DEFAULT 1,
	DB_SVR_ID          NUMERIC(18) NOT NULL,
	RESTORE_NM         VARCHAR(50) NOT NULL,
	RESTORE_EXP        TEXT NULL,
	TIMELINE_DT        VARCHAR(8) NULL,
	TIMELINE_H         VARCHAR(2) NULL,
	TIMELINE_M         VARCHAR(2) NULL,
	TIMELINE_S         VARCHAR(2) NULL,
	DTB_PTH            VARCHAR(300) NULL,
	PGALOG_PTH         VARCHAR(300) NULL,
	SVRLOG_PTH         VARCHAR(300) NULL,
	BCK_PTH            VARCHAR(300) NULL,
	RESTORE_STRTDTM    TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	RESTORE_ENDDTM     TIMESTAMP NULL,
	RESTORE_CNDT       CHAR(1) NOT NULL DEFAULT '0',
	RESTORE_FLAG       CHAR(1) NOT NULL DEFAULT '0',
	ASIS_FLAG          CHAR(1) NOT NULL DEFAULT '0',
        RESTORE_DIR        VARCHAR(100) NULL,
	EXELOG             TEXT NULL,
	REGR_ID            VARCHAR(30) NULL,
	REG_DTM            TIMESTAMP NOT NULL DEFAULT clock_timestamp()

);
ALTER TABLE T_RMAN_RESTORE ADD CONSTRAINT PK_T_RMAN_RESTORE
PRIMARY KEY (RESTORE_SN);

COMMENT ON TABLE T_RMAN_RESTORE IS 'RMAN복구';

COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_SN IS '복구_일련번호';
COMMENT ON COLUMN T_RMAN_RESTORE.DB_SVR_ID IS 'DB서버_아이디';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_NM IS '복구_명';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_EXP IS '복구_설명';
COMMENT ON COLUMN T_RMAN_RESTORE.TIMELINE_DT IS '시점복구_일자';
COMMENT ON COLUMN T_RMAN_RESTORE.TIMELINE_H IS '시점복구_시';
COMMENT ON COLUMN T_RMAN_RESTORE.TIMELINE_M IS '시점복구_분';
COMMENT ON COLUMN T_RMAN_RESTORE.TIMELINE_S IS '시점복구_초';
COMMENT ON COLUMN T_RMAN_RESTORE.DTB_PTH IS '데이터베이스_경로';
COMMENT ON COLUMN T_RMAN_RESTORE.PGALOG_PTH  IS '아카이브월_경로';
COMMENT ON COLUMN T_RMAN_RESTORE.SVRLOG_PTH IS '서버로그_경로';
COMMENT ON COLUMN T_RMAN_RESTORE.BCK_PTH IS '백업_경로';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_STRTDTM IS '복구_시작일시';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_ENDDTM IS '복구_종료일시';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_CNDT IS '복구_상태 : 성공(0), 시작(1), 진행중(2), 실패(3)';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_FLAG IS '복구_구분 긴급복구(0), 시점복구(1)';
COMMENT ON COLUMN T_RMAN_RESTORE.ASIS_FLAG IS '기존/신규 구분 기존(0), 신규(1)';
COMMENT ON COLUMN T_RMAN_RESTORE.RESTORE_DIR IS '복구디렉터리';
COMMENT ON COLUMN T_RMAN_RESTORE.EXELOG IS '실행로그';
COMMENT ON COLUMN T_RMAN_RESTORE.REGR_ID   IS '등록자_ID';
COMMENT ON COLUMN T_RMAN_RESTORE.REG_DTM   IS '등록_일시';


 CREATE TABLE T_DUMP_RESTORE
(
	RESTORE_SN               NUMERIC NOT NULL DEFAULT 1,
	DB_SVR_ID          		 NUMERIC(18) NOT NULL,
	RESTORE_NM               VARCHAR(50) NOT NULL,
	RESTORE_EXP              TEXT NULL,
	WRK_ID                   NUMERIC(18) NOT NULL,
	WRKEXE_SN                NUMERIC(18) NULL,
	RESTORE_STRTDTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	RESTORE_ENDDTM           TIMESTAMP NULL,
	RESTORE_CNDT             CHAR(1) NOT NULL DEFAULT '0',
	EXELOG                   TEXT NULL,

	FORMAT                   VARCHAR(20) NULL,
	FILENAME                 VARCHAR(300) NULL,
	JOBS                     VARCHAR(3) NULL,
	ROLE                     VARCHAR(100) NULL,
	PRE_DATA_YN              CHAR(1) NOT NULL DEFAULT 'N',
	DATA_YN                  CHAR(1) NOT NULL DEFAULT 'N',
	POST_DATA_YN             CHAR(1) NOT NULL DEFAULT 'N',
	DATA_ONLY_YN             CHAR(1) NOT NULL DEFAULT 'N',
	SCHEMA_ONLY_YN           CHAR(1) NOT NULL DEFAULT 'N',
        NO_OWNER_YN              CHAR(1) NOT NULL DEFAULT 'N',
        NO_PRIVILEGES_YN         CHAR(1) NOT NULL DEFAULT 'N',
	NO_TABLESPACES_YN        CHAR(1) NOT NULL DEFAULT 'N',
	CREATE_YN                CHAR(1) NOT NULL DEFAULT 'N',
	CLEAN_YN                 CHAR(1) NOT NULL DEFAULT 'N',
	SINGLE_TRANSACTION_YN    CHAR(1) NOT NULL DEFAULT 'N',
	DISABLE_TRIGGERS_YN      CHAR(1) NOT NULL DEFAULT 'N',
	NO_DATA_FOR_FAILED_TABLES_YN  CHAR(1) NOT NULL DEFAULT 'N',
	VERBOSE_YN               CHAR(1) NOT NULL DEFAULT 'N',
	USE_SET_SESSON_AUTH_YN   CHAR(1) NOT NULL DEFAULT 'N',
	EXIT_ON_ERROR_YN         CHAR(1) NOT NULL DEFAULT 'N',


	REGR_ID            VARCHAR(30) NULL,
	REG_DTM            TIMESTAMP NOT NULL DEFAULT clock_timestamp()

);
ALTER TABLE T_DUMP_RESTORE ADD CONSTRAINT PK_T_DUMP_RESTORE
PRIMARY KEY (RESTORE_SN);

COMMENT ON TABLE T_DUMP_RESTORE IS 'DUMP복구';

COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_SN IS '복구_일련번호';
COMMENT ON COLUMN T_DUMP_RESTORE.DB_SVR_ID IS 'DB서버_아이디';
COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_NM IS '복구_명';
COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_EXP IS '복구_설명';
COMMENT ON COLUMN T_DUMP_RESTORE.WRK_ID IS '작업_ID';
COMMENT ON COLUMN T_DUMP_RESTORE.WRKEXE_SN IS '작업실행_일련번호';
COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_STRTDTM IS '복구_시작일시';
COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_ENDDTM IS '복구_종료일시';
COMMENT ON COLUMN T_DUMP_RESTORE.RESTORE_CNDT IS '복구_상태 : 성공(0), 시작(1), 진행중(2), 실패(3)';
COMMENT ON COLUMN T_DUMP_RESTORE.EXELOG IS '실행로그';
COMMENT ON COLUMN T_DUMP_RESTORE.FORMAT IS 'FORMAT';
COMMENT ON COLUMN T_DUMP_RESTORE.FILENAME IS 'FILENAME';
COMMENT ON COLUMN T_DUMP_RESTORE.JOBS IS 'JOBS';
COMMENT ON COLUMN T_DUMP_RESTORE.ROLE IS 'ROLE';
COMMENT ON COLUMN T_DUMP_RESTORE.PRE_DATA_YN IS 'PRE_DATA_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.DATA_YN IS 'DATA_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.POST_DATA_YN IS 'POST_DATA_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.DATA_ONLY_YN IS 'DATA_ONLY_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.SCHEMA_ONLY_YN IS 'SCHEMA_ONLY_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.NO_OWNER_YN IS 'NO_OWNER_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.NO_PRIVILEGES_YN IS 'NO_PRIVILEGES_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.NO_TABLESPACES_YN IS 'NO_TABLESPACES_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.CREATE_YN IS 'CREATE_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.CLEAN_YN IS 'CLEAN_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.SINGLE_TRANSACTION_YN IS 'SINGLE_TRANSACTION_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.DISABLE_TRIGGERS_YN IS 'DISABLE_TRIGGERS_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.NO_DATA_FOR_FAILED_TABLES_YN IS 'NO_DATA_FOR_FAILED_TABLES_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.VERBOSE_YN IS 'VERBOSE_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.USE_SET_SESSON_AUTH_YN IS 'USE_SET_SESSON_AUTH_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.EXIT_ON_ERROR_YN IS 'EXIT_ON_ERROR_YN';
COMMENT ON COLUMN T_DUMP_RESTORE.REGR_ID IS '등록자_ID';
COMMENT ON COLUMN T_DUMP_RESTORE.REG_DTM IS '등록_일시';


/** 삭제됨
 CREATE TABLE T_EXECMD_WRKCNGINF
(
	EXECMD_WRK_ID        NUMERIC NOT NULL DEFAULT 1,
	WRK_ID               NUMERIC(18) NOT NULL DEFAULT 1,
	DB_SVR_ID            NUMERIC(18) NOT NULL DEFAULT 1,
	EXECMD               TEXT NULL,
	FRST_REGR_ID         VARCHAR(30) NULL,
	FRST_REG_DTM         TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
	LST_MDFR_ID          VARCHAR(30) NULL,
	LST_MDF_DTM          TIMESTAMP NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE T_EXECMD_WRKCNGINF ADD CONSTRAINT PK_T_EXECMD_WRKCNGINF
PRIMARY KEY (EXECMD_WRK_ID);

COMMENT ON TABLE T_EXECMD_WRKCNGINF IS '실행명령_작업설정정보';

 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.EXECMD_WRK_ID IS '실행명령_작업_ID';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.WRK_ID IS '작업_ID';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.DB_SVR_ID IS 'DB_서버_ID';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.EXECMD IS '실행명령';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.FRST_REGR_ID IS '최초_등록자_ID';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.FRST_REG_DTM IS '최초_등록_일시';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.LST_MDFR_ID IS '최종_수정자_ID';
 COMMENT ON COLUMN T_EXECMD_WRKCNGINF.LST_MDF_DTM IS '최종_수정_일시';
**/


ALTER TABLE T_ADTCNG_I
ADD CONSTRAINT  FK_T_ADTCNG_I_01 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);

ALTER TABLE T_ADTCNGDB_I
ADD CONSTRAINT  FK_T_ADTCNGDB_I_01 FOREIGN KEY(DB_ID) REFERENCES T_DB_I (DB_ID);

ALTER TABLE T_ADTCNGDB_I
ADD CONSTRAINT FK_T_ADTCNGDB_I_02 FOREIGN KEY (ADT_CNG_ID) REFERENCES T_ADTCNG_I (ADT_CNG_ID);



ALTER TABLE T_BCKOBJ_L
ADD CONSTRAINT FK_T_BCKOBJ_L_02 FOREIGN KEY (DB_ID) REFERENCES T_DB_I (DB_ID);

/* *********** 2017.06.09 윤진훈 부장님 요청  FK 필요없음
ALTER TABLE T_BCKOPT_I
ADD CONSTRAINT FK_T_BCKOPT_I_01 FOREIGN KEY (WRK_ID) REFERENCES T_WRKCNG_I (WRK_ID);

ALTER TABLE T_BCKOPT_I
ADD CONSTRAINT FK_T_BCKOPT_I_02 FOREIGN KEY (GRP_CD,OPT_CD) REFERENCES T_WRKOPTDTL_C (GRP_CD,OPT_CD);
***************************************** */

ALTER TABLE T_DB_I
ADD CONSTRAINT FK_T_DB_I_01 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);

ALTER TABLE T_MNU_I
ADD CONSTRAINT FK_T_MNU_I_01 FOREIGN KEY (MNU_ID) REFERENCES T_MNU_I (MNU_ID);

ALTER TABLE T_SCD_D
ADD CONSTRAINT FK_T_SCD_D_01 FOREIGN KEY (SCD_ID) REFERENCES T_SCD_M (SCD_ID);




ALTER TABLE T_SVRACSCNTR_I
ADD CONSTRAINT FK_T_SVRACSCNTR_I_02 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);

ALTER TABLE T_SYSDTL_C
ADD CONSTRAINT FK_T_SYSDTL_C_01 FOREIGN KEY (GRP_CD) REFERENCES T_SYSGRP_C (GRP_CD);

/*
  ********** SYSTEM LOG 남기는 TABLE은 FOREIGN KEY를 생성하지 않아도 될듯.
ALTER TABLE T_SYSWRK_G
ADD FOREIGN KEY FK_T_SYSWRK_G_01 (USR_ID) REFERENCES T_USR_I (USR_ID);

ALTER TABLE T_SYSWRK_G
ADD FOREIGN KEY FK_T_SYSWRK_G_02 (MNU_ID) REFERENCES T_MNU_I (MNU_ID);
*/

ALTER TABLE T_TRFMPPTB_L
ADD CONSTRAINT FK_T_TRFMPPTB_L_01 FOREIGN KEY (TRF_TRG_MPP_ID) REFERENCES T_TRFTRGMPP_R (TRF_TRG_MPP_ID);

ALTER TABLE T_TRFTRGCNG_I
ADD CONSTRAINT FK_T_TRFTRGCNG_I_01 FOREIGN KEY (CNR_ID) REFERENCES T_CNR_I (CNR_ID);

ALTER TABLE T_TRFTRGMPP_R
ADD CONSTRAINT FK_T_TRFTRGMPP_R_01 FOREIGN KEY (DB_ID) REFERENCES T_DB_I (DB_ID);

ALTER TABLE T_TRFTRGMPP_R
ADD CONSTRAINT  FK_T_TRFTRGMPP_R_02 FOREIGN KEY (TRF_TRG_ID) REFERENCES T_TRFTRGCNG_I (TRF_TRG_ID);

ALTER TABLE T_TRFTRGMPP_R
ADD CONSTRAINT FK_T_TRFTRGMPP_R_03 FOREIGN KEY (CNR_ID) REFERENCES T_CNR_I (CNR_ID);

ALTER TABLE T_USRDBAUT_I
ADD CONSTRAINT FK_T_USRDBAUT_I_01 FOREIGN KEY (DB_ID) REFERENCES T_DB_I (DB_ID);

ALTER TABLE T_USRDBAUT_I
ADD CONSTRAINT FK_T_USRDBAUT_I_02 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);

ALTER TABLE T_USRDBAUT_I
ADD CONSTRAINT FK_T_USRDBAUT_I_03 FOREIGN KEY (USR_ID) REFERENCES T_USR_I (USR_ID);

ALTER TABLE T_USRDBSVRAUT_I
ADD CONSTRAINT FK_T_USRDBSVRAUT_I_01 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);

ALTER TABLE T_USRDBSVRAUT_I
ADD CONSTRAINT FK_T_USRDBSVRAUT_I_02 FOREIGN KEY (USR_ID) REFERENCES T_USR_I (USR_ID);

ALTER TABLE T_USRLGI_H
ADD CONSTRAINT FK_T_USRLGI_H_01 FOREIGN KEY (USR_ID) REFERENCES T_USR_I (USR_ID);

ALTER TABLE T_USRMNUAUT_I
ADD CONSTRAINT FK_T_USRMNUAUT_I_01 FOREIGN KEY (MNU_ID) REFERENCES T_MNU_I (MNU_ID);

ALTER TABLE T_USRMNUAUT_I
ADD CONSTRAINT FK_T_USRMNUAUT_I_02 FOREIGN KEY (USR_ID) REFERENCES T_USR_I (USR_ID);



/* ******** rman backup인 경우는 전체를 백업 받으므로  db선택이 없다 ***********************
ALTER TABLE T_WRKCNG_I
ADD CONSTRAINT FK_T_WRKCNG_I_02 FOREIGN KEY (DB_ID) REFERENCES T_DB_I (DB_ID);
*/


ALTER TABLE T_WRKOPTDTL_C
ADD CONSTRAINT FK_T_WRKOPTDTL_C_01 FOREIGN KEY (GRP_CD) REFERENCES T_WRKOPTGRP_C (GRP_CD);

ALTER TABLE T_DBSVRIPADR_I
ADD CONSTRAINT FK_T_DBSVRIPADR_I_01 FOREIGN KEY (DB_SVR_ID) REFERENCES T_DBSVR_I (DB_SVR_ID);





CREATE SEQUENCE Q_ADTCNG_I_01      ;
CREATE SEQUENCE Q_ADTCNGDB_I_01    ;
CREATE SEQUENCE Q_AGTCNDT_I_01     ;
CREATE SEQUENCE Q_BCKOBJ_L_01      ;
CREATE SEQUENCE Q_BCKOPT_I_01      ;
CREATE SEQUENCE Q_CNR_I_01         ;
CREATE SEQUENCE Q_DB_I_01          ;
CREATE SEQUENCE Q_DBSVR_I_01       ;
CREATE SEQUENCE Q_MNU_I_01         ;
CREATE SEQUENCE Q_SCD_D_01         ;
CREATE SEQUENCE Q_SCD_M_01         ;
CREATE SEQUENCE Q_SVRACSCNTR_I_01  ;
CREATE SEQUENCE Q_SVRACSCNTR_HIS_I_01  ;
CREATE SEQUENCE Q_SVRACSCNTR_HIS_GRP_I_01  ;
/*                                 ;
CREATE SEQUENCE Q_SYSDTL_C_01      ;
CREATE SEQUENCE Q_SYSGRP_C_01      ;
CREATE SEQUENCE Q_WRKOPTDTL_C_01   ;
CREATE SEQUENCE Q_WRKOPTGRP_C_01   ;
*/                                 ;
                                   ;
CREATE SEQUENCE Q_TRFCNG_I_01      ;
CREATE SEQUENCE Q_TRFMPPTB_L_01    ;
CREATE SEQUENCE Q_TRFTRGCNG_I_01   ;
CREATE SEQUENCE Q_TRFTRGMPP_R_01   ;
CREATE SEQUENCE Q_USR_I_01         ;
CREATE SEQUENCE Q_USRDBAUT_I_01    ;
CREATE SEQUENCE Q_USRDBSVRAUT_I_01 ;
CREATE SEQUENCE Q_USRLGI_H_01      ;
CREATE SEQUENCE Q_USRMNUAUT_I_01   ;
CREATE SEQUENCE Q_WRKCNG_I_01      ;
CREATE SEQUENCE Q_WRKEXE_G_01      ;
CREATE SEQUENCE Q_WRKEXE_G_02      ;
CREATE SEQUENCE Q_SYSWRK_G_01      ;
CREATE SEQUENCE Q_DUMP_01;
CREATE SEQUENCE Q_BCK_WRKCNG_I;

CREATE SEQUENCE Q_DBSVRIPADR_I_01 ;

CREATE SEQUENCE Q_RMAN_RESTORE_01 ;
CREATE SEQUENCE Q_DUMP_RESTORE_01 ;


